services:
  - type: web
    name: evnest-backend
    plan: free
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: PORT
        value: 10000
